CREATE TABLE IF NOT EXISTS PUBLIC.FILMS (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NAME CHARACTER VARYING(50) NOT NULL,
	DESCRIPTION CHARACTER VARYING(200),
	RELEASE_DATE DATE,
	DURATION INTEGER,
	ID_MPA SMALLINT,
	CONSTRAINT FILMS_PK PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS PUBLIC.USERS (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NAME CHARACTER VARYING(50),
	email CHARACTER VARYING(50) NOT NULL,
	login CHARACTER VARYING(50) NOT NULL,
	birthday DATE,
	CONSTRAINT USERS_PK PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS PUBLIC.GENRES (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NAME CHARACTER VARYING(50) NOT NULL,
	CONSTRAINT GENRES_PK PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS PUBLIC.USER_LIKES (
    ID INTEGER NOT NULL AUTO_INCREMENT,
	ID_USER INTEGER,
	ID_FILM INTEGER,
	CONSTRAINT USERS_LIKES_PK PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS PUBLIC.FILM_GENRES (
    ID INTEGER NOT NULL AUTO_INCREMENT,
	ID_GENRE INTEGER NOT NULL,
	ID_FILM INTEGER NOT NULL,
	CONSTRAINT FILM_GENRES_PK PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS PUBLIC.MPA (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NAME CHARACTER VARYING(50),
	DESCRIPTION CHARACTER VARYING(100),
	CONSTRAINT MPA_PK PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS PUBLIC.FRIENDS (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	ID_USER INTEGER,
	CONFIRMED BOOLEAN,
	ID_FRIEND INTEGER,
	CONSTRAINT FRIENDS_PK PRIMARY KEY (ID)
);
